[wokwi]
version = 1
firmware = '.pio/build/esp32doit-devkit-v1/firmware.bin'
elf = '.pio/build/esp32doit-devkit-v1/firmware.elf'

[[chip]]
name = 'soil-sensor'
binary = 'soil-sensor.chip.wasm'

[[chip]]
name = 'chip-soil-sensor'
binary = 'soil-sensor.chip.wasm'